### ISSUE TITLE
All the links are broken

### ISSUE THREAD

**Issue by jennyfothergill** [cmelab/getting-started#1]
The links don't work after porting from bitbucket

**Comment by erjank** [comment]
Looks like we need to append .md to all the links, plus https://github.com/cmelab/getting-started/blob/master/wiki/ at the beginning

**Comment by jennyfothergill** [comment]
For intra-repo links we can use relative paths:
```
-+- README.md
 |
 +- wiki/ -+- wikipage.md
           |
           +- other_wikipage.md
```
for example if we wanted to put a link to `wikipage.md` in `README.md` we could do
```
[click here to go to wikipage](wiki/wikipage.md)
```

**Comment by jennyfothergill** [comment]
all links work on `README.md` and `wiki/README.md` and all files linked from those.
