### ISSUE TITLE
Update Setting up on OSX instructions

### ISSUE THREAD

**Issue by miaklop** [cmelab/getting-started#27]
In the 'Download Miniconda!' section:

The command, 'conda source', does not work (getting a CommandNotFoundError).

I think the command might be outdated, so I suggest removing it or changing it to something else.

**Comment by jennyfothergill** [comment]
check with #18 to make sure there is not overlap

**Comment by miaklop** [comment]
Duplicates right before the vmd catalina stuff:

`cp vmdrc ~/.vmdrc
cp vimrc ~/.vimrc`

There's two of these^.
